#!/usr/bin/python3
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "modules/lib"))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "modules/lib/shell"))
import editor
editor.main()