# Form implementation generated from reading ui file 'camflasher.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.lay_window = QtWidgets.QWidget(MainWindow)
        self.lay_window.setObjectName("lay_window")
        self.gridLayout = QtWidgets.QGridLayout(self.lay_window)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_main = QtWidgets.QGridLayout()
        self.lay_main.setObjectName("lay_main")
        self.lbl_port = QtWidgets.QLabel(self.lay_window)
        self.lbl_port.setObjectName("lbl_port")
        self.lay_main.addWidget(self.lbl_port, 0, 0, 1, 1)
        self.cbo_port = QtWidgets.QComboBox(self.lay_window)
        self.cbo_port.setObjectName("cbo_port")
        self.lay_main.addWidget(self.cbo_port, 0, 1, 1, 1)
        self.chk_erase = QtWidgets.QCheckBox(self.lay_window)
        self.chk_erase.setObjectName("chk_erase")
        self.lay_main.addWidget(self.chk_erase, 0, 2, 1, 1)
        self.lbl_firmware = QtWidgets.QLabel(self.lay_window)
        self.lbl_firmware.setObjectName("lbl_firmware")
        self.lay_main.addWidget(self.lbl_firmware, 1, 0, 1, 1)
        self.txt_firmware = QtWidgets.QLineEdit(self.lay_window)
        self.txt_firmware.setObjectName("txt_firmware")
        self.lay_main.addWidget(self.txt_firmware, 1, 1, 1, 1)
        self.but_firmware = QtWidgets.QPushButton(self.lay_window)
        self.but_firmware.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_firmware.sizePolicy().hasHeightForWidth())
        self.but_firmware.setSizePolicy(sizePolicy)
        self.but_firmware.setAcceptDrops(True)
        self.but_firmware.setObjectName("but_firmware")
        self.lay_main.addWidget(self.but_firmware, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.lay_main, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(319, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.but_flash = QtWidgets.QPushButton(self.lay_window)
        self.but_flash.setObjectName("but_flash")
        self.gridLayout.addWidget(self.but_flash, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.txt_result = QtWidgets.QTextBrowser(self.lay_window)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.txt_result.setFont(font)
        self.txt_result.setObjectName("txt_result")
        self.gridLayout.addWidget(self.txt_result, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.lay_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CamFlasher"))
        self.lbl_port.setText(_translate("MainWindow", "Serial port"))
        self.cbo_port.setToolTip(_translate("MainWindow", "Plug device and select serial port"))
        self.chk_erase.setToolTip(_translate("MainWindow", "Check to erase the flash content before write firmware"))
        self.chk_erase.setText(_translate("MainWindow", "Erase flash"))
        self.lbl_firmware.setText(_translate("MainWindow", "Firmware"))
        self.txt_firmware.setToolTip(_translate("MainWindow", "Enter firmware name"))
        self.but_firmware.setToolTip(_translate("MainWindow", "Select firmware file"))
        self.but_firmware.setText(_translate("MainWindow", "..."))
        self.but_flash.setToolTip(_translate("MainWindow", "Start the flash of firmware"))
        self.but_flash.setText(_translate("MainWindow", "Flash firmware"))
