# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogflash.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFlash(object):
    def setupUi(self, DialogFlash):
        DialogFlash.setObjectName("DialogFlash")
        DialogFlash.resize(600, 218)
        self.gridLayout = QtWidgets.QGridLayout(DialogFlash)
        self.gridLayout.setObjectName("gridLayout")
        self.label_firmware = QtWidgets.QLabel(DialogFlash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_firmware.sizePolicy().hasHeightForWidth())
        self.label_firmware.setSizePolicy(sizePolicy)
        self.label_firmware.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_firmware.setObjectName("label_firmware")
        self.gridLayout.addWidget(self.label_firmware, 0, 0, 1, 1)
        self.firmware_layout = QtWidgets.QHBoxLayout()
        self.firmware_layout.setObjectName("firmware_layout")
        self.firmware = QtWidgets.QLineEdit(DialogFlash)
        self.firmware.setObjectName("firmware")
        self.firmware_layout.addWidget(self.firmware)
        self.select_firmware = QtWidgets.QPushButton(DialogFlash)
        self.select_firmware.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_firmware.sizePolicy().hasHeightForWidth())
        self.select_firmware.setSizePolicy(sizePolicy)
        self.select_firmware.setAcceptDrops(True)
        self.select_firmware.setObjectName("select_firmware")
        self.firmware_layout.addWidget(self.select_firmware)
        self.gridLayout.addLayout(self.firmware_layout, 1, 0, 1, 2)
        self.label_baud = QtWidgets.QLabel(DialogFlash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_baud.sizePolicy().hasHeightForWidth())
        self.label_baud.setSizePolicy(sizePolicy)
        self.label_baud.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.label_baud.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_baud.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_baud.setObjectName("label_baud")
        self.gridLayout.addWidget(self.label_baud, 2, 0, 1, 1)
        self.baud_layout = QtWidgets.QHBoxLayout()
        self.baud_layout.setObjectName("baud_layout")
        self.baud = QtWidgets.QComboBox(DialogFlash)
        self.baud.setEnabled(True)
        self.baud.setMinimumSize(QtCore.QSize(150, 0))
        self.baud.setObjectName("baud")
        self.baud_layout.addWidget(self.baud)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.baud_layout.addItem(spacerItem)
        self.gridLayout.addLayout(self.baud_layout, 3, 0, 1, 2)
        self.erase = QtWidgets.QCheckBox(DialogFlash)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erase.sizePolicy().hasHeightForWidth())
        self.erase.setSizePolicy(sizePolicy)
        self.erase.setObjectName("erase")
        self.gridLayout.addWidget(self.erase, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.button_box = QtWidgets.QDialogButtonBox(DialogFlash)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 6, 0, 1, 2)

        self.retranslateUi(DialogFlash)
        self.button_box.accepted.connect(DialogFlash.accept) # type: ignore
        self.button_box.rejected.connect(DialogFlash.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogFlash)
        DialogFlash.setTabOrder(self.firmware, self.select_firmware)
        DialogFlash.setTabOrder(self.select_firmware, self.baud)
        DialogFlash.setTabOrder(self.baud, self.erase)

    def retranslateUi(self, DialogFlash):
        _translate = QtCore.QCoreApplication.translate
        DialogFlash.setWindowTitle(_translate("DialogFlash", "Flash firmware"))
        self.label_firmware.setText(_translate("DialogFlash", "Firmware"))
        self.firmware.setToolTip(_translate("DialogFlash", "Enter firmware file"))
        self.select_firmware.setToolTip(_translate("DialogFlash", "Select firmware file"))
        self.select_firmware.setText(_translate("DialogFlash", "..."))
        self.label_baud.setText(_translate("DialogFlash", "Baud rate"))
        self.baud.setToolTip(_translate("DialogFlash", "Select flash baud rate"))
        self.erase.setToolTip(_translate("DialogFlash", "Check to erase the flash content before write firmware"))
        self.erase.setText(_translate("DialogFlash", "Erase flash"))
