# Form implementation generated from reading ui file 'dialogoption.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogOption(object):
    def setupUi(self, DialogOption):
        DialogOption.setObjectName("DialogOption")
        DialogOption.resize(600, 185)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogOption)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_working_directory = QtWidgets.QLabel(DialogOption)
        self.label_working_directory.setObjectName("label_working_directory")
        self.verticalLayout.addWidget(self.label_working_directory)
        self.directory_layout = QtWidgets.QHBoxLayout()
        self.directory_layout.setObjectName("directory_layout")
        self.working_directory = QtWidgets.QLineEdit(DialogOption)
        self.working_directory.setObjectName("working_directory")
        self.directory_layout.addWidget(self.working_directory)
        self.select_directory = QtWidgets.QPushButton(DialogOption)
        self.select_directory.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_directory.sizePolicy().hasHeightForWidth())
        self.select_directory.setSizePolicy(sizePolicy)
        self.select_directory.setAcceptDrops(True)
        self.select_directory.setObjectName("select_directory")
        self.directory_layout.addWidget(self.select_directory)
        self.verticalLayout.addLayout(self.directory_layout)
        self.label_console_font = QtWidgets.QLabel(DialogOption)
        self.label_console_font.setObjectName("label_console_font")
        self.verticalLayout.addWidget(self.label_console_font)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_font = QtWidgets.QFontComboBox(DialogOption)
        self.combo_font.setEditable(False)
        self.combo_font.setFontFilters(QtWidgets.QFontComboBox.FontFilter.MonospacedFonts)
        self.combo_font.setObjectName("combo_font")
        self.horizontalLayout.addWidget(self.combo_font)
        self.spin_font_size = QtWidgets.QSpinBox(DialogOption)
        self.spin_font_size.setMinimum(7)
        self.spin_font_size.setMaximum(50)
        self.spin_font_size.setObjectName("spin_font_size")
        self.horizontalLayout.addWidget(self.spin_font_size)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogOption)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogOption)
        self.buttonBox.accepted.connect(DialogOption.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogOption.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogOption)

    def retranslateUi(self, DialogOption):
        _translate = QtCore.QCoreApplication.translate
        DialogOption.setWindowTitle(_translate("DialogOption", "Options"))
        self.label_working_directory.setText(_translate("DialogOption", "Working directory"))
        self.working_directory.setToolTip(_translate("DialogOption", "Working directory for exchanging files with the device"))
        self.select_directory.setToolTip(_translate("DialogOption", "Select firmware file"))
        self.select_directory.setText(_translate("DialogOption", "..."))
        self.label_console_font.setText(_translate("DialogOption", "Console font"))
