# Distributed under MIT License
# Copyright (c) 2021 Remi BERTHOLET
""" Textes en francais pour watt metre """
title_electricmeter = b"Puissance consomm\xC3\xA9e "
menu_electricmeter  = b"Compteur"

item_hour           = b"Par heure"
rate                = b"Tarif"
field_rate          = b"Nom d\xC3\xA9finissant le tarif"
price               = b"Prix au kwh"
currency            = b"Devise"
field_currency      = b"Devise \xc3\xa0 utiliser pour le tarif"
validy_date         = b"Date de validit\xC3\xA9"
step_minutes        = b"minutes"
name                = b"Nom"
type_price          = b"Prix"
type_power          = b"kWh"

title_rate          = b"Tarif du kWh"
add_button          = b"Ajouter"
remove_button       = b"\xF0\x9F\x97\x91"
from_the            = b"par kWh, "
remove_dialog       = b"Voulez vous supprimer ?"

item_time_slots     = b"Plages horaire"
title_time_slots    = b"Plages horaire"
field_start         = b"Heure de d\xC3\xA9but"
field_end           = b"Heure de fin"
field_time_rate     = b"Nom du tarif"
field_color         = b"Couleur du tarif"

item_day            = b"Par jour"
item_month          = b"Par mois"
item_year           = b"Par ann\xC3\xA9e"
item_rate           = b"Tarif"
power_consumed      = b"Puissance instantan\xC3\xA9e"
