# Distributed under MIT License
# Copyright (c) 2021 Remi BERTHOLET
""" English text for electricmeter """
title_electricmeter = b"Power consumption per "
menu_electricmeter  = b"Electric meter"

rate                = b"Rate"
field_rate          = b"Name defining the rate"
price               = b"Price per kWh"
currency            = b"Currency"
field_currency      = b"Currency to be used for the fare"
validy_date         = b"Validity date"
step_minutes        = b"minutes"
name                = b"Name"
type_price          = b"Prix"
type_power          = b"kWh"

title_rate          = b"Rate per kWh"
add_button          = b"Add"
remove_button       = b"\xF0\x9F\x97\x91"
from_the            = b"per kWh, "
remove_dialog       = b"do you want to delete ?"

item_time_slots     = b"Time slots"
title_time_slots    = b"Time slots"
field_start         = b"Start time"
field_end           = b"End time"
field_time_rate     = b"Rate name"
field_color         = b"Rate color"

item_hour           = b"Hour"
item_day            = b"Day"
item_month          = b"Month"
item_year           = b"Year"
item_rate           = b"Rate"
power_consumed      = b"Instantaneous power consumption"
