# Distributed under Pycameresp License
# Copyright (c) 2023 Remi BERTHOLET
""" English text for sourdough bread """
title_sourdoughbread = b"Sourdough bread"
menu_sourdoughbread  = b"Sourdough bread"
humidity             = b"Humidity coefficient (&#37;)"
flour                = b"Flour (g)"
leaven               = b"Leaven (g)"
compute              = b"Compute"
reset                = b"Reset"
water                = b"Water (g)"
weight               = b"Total weight (g)"
bread_weight         = b"Bread weight (g)"
seed                 = b"Seed (g)"
quantity             = b"Number of bread"
percent_leaven       = b"Leaven percent (should be between 25 and 50&#37;)"
