# Distributed under Pycameresp License
# Copyright (c) 2023 Remi BERTHOLET
""" Textes en francais pour le pain au levain """
title_sourdoughbread = b"Pain au levain"
menu_sourdoughbread  = b"Pain levain"
humidity             = b"Co\xC3\xA9fficient d'humidit\xC3\xA9 (&#37;)"
flour                = b"Farine (g)"
leaven               = b"Levain (g)"
compute              = b"Calculer"
water                = b"Eau (g)"
weight               = b"Poids total (g)"
bread_weight         = b"Poids par pain (g)"
seed                 = b"Graines (g)"
quantity             = b"Nombre de pains"
percent_leaven       = b"Pourcentage de levain (doit \xC3\xAAtre entre 25 et 50&#37;)"
